Resolves #7: Fundament for git check status implemented
Atema/DD2480-CI pull request #14
Opened 2021-02-06 14:17 UTC by hallon-heyman

2021-02-07 22:15 UTC, Atema commented
Appearantly, the switch with arrows (`->`) is only supported by java 14+, so better to change that back to a regular one.

2021-02-07 22:16 UTC, Atema commented on src/main/java/BuildResult.java
> +            case FAILURE -> body.put("state", "failure");
Apparently, the `->` cases are only supported by java 14+, so better to change that back to regular ones.

2021-02-07 22:34 UTC, Atema commented on src/main/java/BuildResult.java
> +            case FAILURE -> body.put("state", "failure");
Once PR #21 has been merged, that one can be used with `toString`

2021-02-09 14:54 UTC, Atema commented on src/test/java/BuildResultTests.java
> + * The tests can only truly be checked by checking the GitPage.
That's not necessarily true. Since you receive a response from GitHub, you could check if that's successfull

2021-02-09 14:56 UTC, Atema commented on src/main/java/BuildResult.java
> +            HttpResponse<String> response = Unirest.post(""+ this.build.statusURL + this.build.idSHA)
I'm not sure what format statusURL will be in (I will check in a moment), but I think this may not work.

2021-02-09 15:06 UTC, Atema commented on src/main/java/BuildResult.java
> +            HttpResponse<String> response = Unirest.post(""+ this.build.statusURL + this.build.idSHA)
`build.statusURL` has the format `https://api.github.com/repos/Atema/DD2480-CI/statuses/{sha}`, so you'll have to replace `{sha}` by the SHA. Also, please don't use `this` if not necessary

2021-02-09 17:02 UTC, Atema requested changes

2021-02-09 17:02 UTC, Atema commented on src/main/java/BuildResult.java
> +        gitResponse = responseJSON.getString("status");
I wouldn't store `gitResponse` as a class property. Instead, I would let the function return it.

2021-02-09 17:02 UTC, Atema commented on src/test/java/BuildResultTests.java
> +    Build build =  new Build("", "", "", "", "", "", "", "");
Some build properties should be set; the test should run on a real commit (otherwise, there's no state to set)

2021-02-09 17:02 UTC, Atema commented on src/test/java/BuildResultTests.java
> +    JSONobject response = new JSONobject(buildResult.gitResponse);
No JSONObjects necessary if it's already a String

2021-02-09 17:13 UTC, hallon-heyman commented on src/main/java/BuildResult.java
> +        gitResponse = responseJSON.getString("status");
It won't let me return the HTTPresponse

2021-02-09 22:59 UTC, merged