Issue/9 implement build function
Atema/DD2480-CI pull request #26
Opened 2021-02-08 16:09 UTC by aoutir

2021-02-08 17:09 UTC, Atema commented
@aoutir Try to add a property to the BuildResult class that stores the build logs. If some Java error happens in the process (for example thrown by the `cloneRepo` method), that should be reported with an ERROR status, with the error outputted to the build log. If the build completes, it should report a FAILURE or SUCCESS status, and include the output of running the build as the build log.

2021-02-09 16:46 UTC, Atema requested changes

2021-02-09 16:46 UTC, Atema commented on src/main/java/Build.java
> +        }
In both cases, both the stdout and stderr should be included in the log. `p.redirectErrorStream(true)` can be used to ensure the errorStream is included the inputStream. If that's executed, `p.getInputStream()` should be used for both.

2021-02-09 16:46 UTC, Atema commented on src/main/java/Build.java
> +    public BuildResult build(Build b) throws IOException, InterruptedException {
`IOException` and `InterruptedException` should be caught and returned as a `BuildResult` with `BuildStatus.ERROR`.

2021-02-09 16:46 UTC, Atema commented on src/main/java/Build.java
> +            result = new BuildResult(b,BuildStatus.ERROR,"Failed to clone repository");
Instead of `"Failed to clone repository"`, perhaps it's better to use `e.getMessage()`, which will return more information about the error.

2021-02-09 16:46 UTC, Atema commented on src/main/java/Build.java
>       * @throws IOException throw by cloneRepo
All errors that are not thrown by the function should be removed. (In the end, it shouldn't throw any errors, but always return a `BuildResult` with `BuildStatus.ERROR` instead

2021-02-09 17:13 UTC, aoutir commented on src/main/java/Build.java
> +    public BuildResult build(Build b) throws IOException, InterruptedException {
the `IOException` and `InterruptedException` are there because of the start function so you think I should surround the         `Process pr = p.start();` with a try and catch and return a `buildResult` ?

2021-02-09 23:04 UTC, merged